"""Execution bounded-context contracts and PostgreSQL adapters."""

from .artifact_tables import (
    artifact_metadata,
    client_artifacts,
    client_exchange_evidence,
)
from .artifacts import (
    ClientArtifactRetentionPort,
    ClientExchangeEvidence,
    ClientExchangeEvidenceReader,
    ClientExchangeEvidenceWriter,
    ClientRequestArtifactWriter,
    ClientResultArtifactReader,
    ClientResultArtifactWriter,
    SanitizedEvidenceRecord,
)
from .attempt_postgres import PostgresProviderAttemptStore
from .attempt_tables import attempt_metadata, provider_attempts
from .attempts import (
    DispatchAction,
    DispatchClaim,
    ProviderAttempt,
    ProviderAttemptStatus,
    ProviderAttemptStore,
)
from .client_api_idempotency import (
    ClientApiIdempotencyConflict,
    ClientApiIdempotencyJournal,
    ClientApiIdempotencyReservation,
    InMemoryClientApiIdempotencyJournal,
)
from .client_api_postgres import PostgresClientApiIdempotencyJournal
from .client_api_tables import client_api_idempotency
from .retention import (
    ArtifactRetentionCutoffs,
    ClientArtifactRetentionCoordinator,
    ClientArtifactRetentionPolicy,
    ClientArtifactRetentionStore,
    DEFAULT_CLIENT_ARTIFACT_RETENTION_POLICY,
    RetentionHold,
    RetentionPurgeResult,
)
from .orchestration import (
    AttemptObservation,
    AttemptObservationStatus,
    CanonicalOrchestrationPolicyEngine,
    OrchestrationCandidate,
    OrchestrationCyclePlan,
    OrchestrationDecision,
    OrchestrationDisposition,
    OrchestrationPolicy,
    RequirementProgress,
    rank_auto_candidates,
)
from .postgres import PostgresExecutionSessionStore
from .sessions import (
    ExecutionSession,
    ExecutionSessionStore,
    ExecutionTargetSnapshot,
    OwnershipScope,
    QuarantineState,
    SessionPolicySnapshot,
    SessionStatus,
    TargetHealth,
    TargetRuntimeState,
)
from .tables import execution_metadata, execution_sessions, session_target_runtime
from .task_postgres import PostgresExecutionTaskStore
from .task_tables import (
    task_cycle_decisions,
    task_metadata,
    task_transitions,
    tasks,
)
from .tasks import (
    VALID_TRANSITIONS,
    ExecutionMode,
    ExecutionTask,
    ExecutionTaskStore,
    RequestedTargetSnapshot,
    TaskCycleDecision,
    TaskPayloadReferences,
    TaskReasonEnvelope,
    TaskStatus,
    validate_requirement_partition,
    validate_transition,
)

__all__ = [
    "AttemptObservation",
    "AttemptObservationStatus",
    "CanonicalOrchestrationPolicyEngine",
    "ClientApiIdempotencyConflict",
    "ClientApiIdempotencyJournal",
    "ClientApiIdempotencyReservation",
    "ArtifactRetentionCutoffs",
    "ClientArtifactRetentionCoordinator",
    "ClientArtifactRetentionPolicy",
    "ClientArtifactRetentionPort",
    "ClientArtifactRetentionStore",
    "ClientExchangeEvidence",
    "ClientExchangeEvidenceReader",
    "ClientExchangeEvidenceWriter",
    "ClientRequestArtifactWriter",
    "ClientResultArtifactReader",
    "ClientResultArtifactWriter",
    "DEFAULT_CLIENT_ARTIFACT_RETENTION_POLICY",
    "DispatchAction",
    "DispatchClaim",
    "ExecutionMode",
    "ExecutionSession",
    "ExecutionSessionStore",
    "ExecutionTargetSnapshot",
    "ExecutionTask",
    "ExecutionTaskStore",
    "InMemoryClientApiIdempotencyJournal",
    "OrchestrationCandidate",
    "OrchestrationCyclePlan",
    "OrchestrationDecision",
    "OrchestrationDisposition",
    "OrchestrationPolicy",
    "OwnershipScope",
    "PostgresClientApiIdempotencyJournal",
    "PostgresExecutionSessionStore",
    "PostgresExecutionTaskStore",
    "PostgresProviderAttemptStore",
    "ProviderAttempt",
    "ProviderAttemptStatus",
    "ProviderAttemptStore",
    "QuarantineState",
    "RequestedTargetSnapshot",
    "RequirementProgress",
    "RetentionHold",
    "RetentionPurgeResult",
    "SanitizedEvidenceRecord",
    "SessionPolicySnapshot",
    "SessionStatus",
    "TargetHealth",
    "TargetRuntimeState",
    "TaskCycleDecision",
    "TaskPayloadReferences",
    "TaskReasonEnvelope",
    "TaskStatus",
    "VALID_TRANSITIONS",
    "artifact_metadata",
    "attempt_metadata",
    "client_api_idempotency",
    "client_artifacts",
    "client_exchange_evidence",
    "execution_metadata",
    "execution_sessions",
    "provider_attempts",
    "rank_auto_candidates",
    "session_target_runtime",
    "task_cycle_decisions",
    "task_metadata",
    "task_transitions",
    "tasks",
    "validate_requirement_partition",
    "validate_transition",
]
