"""Secure, rebuildable Web Read Model contracts."""

from .cache import CacheLookup, InMemoryReadModelCache
from .domain import (
    SURFACE_POLICIES,
    ProjectionFreshness,
    ProjectionIdentity,
    ReadAudience,
    ReadClassification,
    ReadModelDocument,
    ReadSurface,
    SurfacePolicy,
)
from .intelligence import (
    ExternalCapacityIndicator,
    ExternalCapacityIndicatorSource,
    IntelligenceDimension,
    IntelligenceDimensionValue,
    IntelligenceMetrics,
    IntelligenceQuery,
    IntelligenceRow,
    OperationalFinancialIntelligenceService,
    OperationalIntelligenceResult,
    QuotaUtilizationIndicator,
    QuotaUtilizationIndicatorSource,
)
from .pagination import CursorPage, decode_cursor, encode_cursor, paginate
from .reporting import (
    CLIENT_USAGE_MAX_SOURCE_ROWS,
    REPORT_MAX_QUERY_SPAN,
    REPORT_STORE_MAX_ROWS,
    BackofficeReportAccess,
    BackofficeReportingService,
    BackofficeReportPage,
    BoundedReadExceeded,
    ClientUsageBucket,
    ClientUsagePage,
    ClientUsageReportService,
    InMemoryReportExportAuditSink,
    InMemoryReportRollupStore,
    ReportExportAuditEvent,
    ReportExportAuditSink,
    ReportQuery,
    ReportRollup,
    ReportRollupStore,
)
from .reporting_postgres import PostgresReportRollupStore
from .reporting_tables import report_rollups
from .store import PostgresReadModelStore, ReadModelStore
from .tables import projection_documents

__all__ = [
    "BackofficeReportAccess",
    "BoundedReadExceeded",
    "CLIENT_USAGE_MAX_SOURCE_ROWS",
    "REPORT_MAX_QUERY_SPAN",
    "REPORT_STORE_MAX_ROWS",
    "BackofficeReportPage",
    "BackofficeReportingService",
    "CacheLookup",
    "ClientUsageBucket",
    "ClientUsagePage",
    "ClientUsageReportService",
    "CursorPage",
    "ExternalCapacityIndicator",
    "ExternalCapacityIndicatorSource",
    "InMemoryReadModelCache",
    "InMemoryReportExportAuditSink",
    "InMemoryReportRollupStore",
    "IntelligenceDimension",
    "IntelligenceDimensionValue",
    "IntelligenceMetrics",
    "IntelligenceQuery",
    "IntelligenceRow",
    "PostgresReadModelStore",
    "OperationalFinancialIntelligenceService",
    "OperationalIntelligenceResult",
    "PostgresReportRollupStore",
    "QuotaUtilizationIndicator",
    "QuotaUtilizationIndicatorSource",
    "ProjectionFreshness",
    "ProjectionIdentity",
    "ReadAudience",
    "ReadClassification",
    "ReadModelDocument",
    "ReadModelStore",
    "ReadSurface",
    "ReportExportAuditEvent",
    "ReportExportAuditSink",
    "ReportQuery",
    "ReportRollup",
    "ReportRollupStore",
    "SURFACE_POLICIES",
    "SurfacePolicy",
    "decode_cursor",
    "encode_cursor",
    "paginate",
    "projection_documents",
    "report_rollups",
]
