"""Provider adapter contracts, registry contracts and deterministic test-provider support."""

from .deepseek import DEEPSEEK_RESPONSES_ENDPOINT, DeepSeekResponsesAdapter
from .io import (
    ProviderCredential,
    ProviderInvocationPayload,
    ProviderRequestPayloadReader,
    ProviderResponsePayloadWriter,
    StructuredOutputSpec,
    StructuredOutputValidator,
)
from .openai import OPENAI_RESPONSES_ENDPOINT, OpenAIResponsesAdapter
from .parity import (
    CANONICAL_PROVIDER_PORT_PLAN,
    MANDATORY_ADAPTER_PARITY_GATES,
    AdapterParityGate,
    AdapterTransportFamily,
    ProviderPortPlan,
    provider_port_plan,
)
from .protocol import (
    NativeUsage,
    OutputKind,
    ProviderAdapter,
    ProviderAttemptRequest,
    ProviderAttemptResult,
    ProviderCostMetadata,
    ProviderOutcome,
    ProviderTarget,
    ProviderUsage,
)
from .registry import (
    INITIAL_PROVIDER_TAXONOMY,
    AdapterResolution,
    ProviderCapability,
    ProviderModelSpec,
    ProviderRegistry,
    ProviderRegistryError,
    ProviderRegistryReader,
    ProviderSpec,
    PublicProviderTargetMetadata,
    ReasoningProfileSpec,
    RegistryEligibilityMode,
    RegistryFailureCode,
    RequestedTargetIdentity,
    ResolvedProviderTarget,
    TargetIdentity,
)
from .responses import (
    HttpxProviderHttpTransport,
    ProviderDispatchAmbiguousError,
    ProviderHttpResponse,
    ProviderHttpTransport,
    ResponsesHttpAdapter,
)
from .simulator import (
    ORQETIA_TEST_PROVIDER,
    DeterministicTestProvider,
    SimulatorCandidate,
    SimulatorFixture,
    SimulatorFixtureExhausted,
    SimulatorFixtureMismatch,
    SimulatorInvocation,
    SimulatorScenario,
    SimulatorStep,
)

__all__ = [
    "CANONICAL_PROVIDER_PORT_PLAN",
    "DEEPSEEK_RESPONSES_ENDPOINT",
    "OPENAI_RESPONSES_ENDPOINT",
    "INITIAL_PROVIDER_TAXONOMY",
    "MANDATORY_ADAPTER_PARITY_GATES",
    "AdapterParityGate",
    "AdapterTransportFamily",
    "ORQETIA_TEST_PROVIDER",
    "AdapterResolution",
    "DeepSeekResponsesAdapter",
    "DeterministicTestProvider",
    "HttpxProviderHttpTransport",
    "NativeUsage",
    "OpenAIResponsesAdapter",
    "OutputKind",
    "ProviderAdapter",
    "ProviderAttemptRequest",
    "ProviderCredential",
    "ProviderDispatchAmbiguousError",
    "ProviderHttpResponse",
    "ProviderHttpTransport",
    "ProviderInvocationPayload",
    "ProviderAttemptResult",
    "ProviderCapability",
    "ProviderCostMetadata",
    "ProviderModelSpec",
    "ProviderOutcome",
    "ProviderPortPlan",
    "ProviderRegistry",
    "ProviderRegistryError",
    "ProviderRegistryReader",
    "ProviderRequestPayloadReader",
    "ProviderResponsePayloadWriter",
    "ResponsesHttpAdapter",
    "ProviderSpec",
    "ProviderTarget",
    "ProviderUsage",
    "PublicProviderTargetMetadata",
    "ReasoningProfileSpec",
    "RegistryEligibilityMode",
    "RegistryFailureCode",
    "RequestedTargetIdentity",
    "ResolvedProviderTarget",
    "SimulatorCandidate",
    "SimulatorFixture",
    "SimulatorFixtureExhausted",
    "SimulatorFixtureMismatch",
    "SimulatorInvocation",
    "SimulatorScenario",
    "SimulatorStep",
    "StructuredOutputSpec",
    "StructuredOutputValidator",
    "TargetIdentity",
    "provider_port_plan",
]
