"""Provider adapter contracts, registry contracts and deterministic test-provider support."""

from .protocol import (
    NativeUsage,
    OutputKind,
    ProviderAdapter,
    ProviderAttemptRequest,
    ProviderAttemptResult,
    ProviderCostMetadata,
    ProviderOutcome,
    ProviderTarget,
    ProviderUsage,
)
from .registry import (
    INITIAL_PROVIDER_TAXONOMY,
    AdapterResolution,
    ProviderCapability,
    ProviderModelSpec,
    ProviderRegistry,
    ProviderRegistryError,
    ProviderRegistryReader,
    ProviderSpec,
    PublicProviderTargetMetadata,
    ReasoningProfileSpec,
    RegistryEligibilityMode,
    RegistryFailureCode,
    RequestedTargetIdentity,
    ResolvedProviderTarget,
    TargetIdentity,
)
from .simulator import (
    ORQETIA_TEST_PROVIDER,
    DeterministicTestProvider,
    SimulatorCandidate,
    SimulatorFixture,
    SimulatorFixtureExhausted,
    SimulatorFixtureMismatch,
    SimulatorInvocation,
    SimulatorScenario,
    SimulatorStep,
)

__all__ = [
    "INITIAL_PROVIDER_TAXONOMY",
    "ORQETIA_TEST_PROVIDER",
    "AdapterResolution",
    "DeterministicTestProvider",
    "NativeUsage",
    "OutputKind",
    "ProviderAdapter",
    "ProviderAttemptRequest",
    "ProviderAttemptResult",
    "ProviderCapability",
    "ProviderCostMetadata",
    "ProviderModelSpec",
    "ProviderOutcome",
    "ProviderRegistry",
    "ProviderRegistryError",
    "ProviderRegistryReader",
    "ProviderSpec",
    "ProviderTarget",
    "ProviderUsage",
    "PublicProviderTargetMetadata",
    "ReasoningProfileSpec",
    "RegistryEligibilityMode",
    "RegistryFailureCode",
    "RequestedTargetIdentity",
    "ResolvedProviderTarget",
    "SimulatorCandidate",
    "SimulatorFixture",
    "SimulatorFixtureExhausted",
    "SimulatorFixtureMismatch",
    "SimulatorInvocation",
    "SimulatorScenario",
    "SimulatorStep",
    "TargetIdentity",
]
