"""Provider adapter contracts, registry contracts and deterministic test-provider support."""

from .anthropic import (
    ANTHROPIC_MESSAGES_ENDPOINT,
    ANTHROPIC_VERSION,
    AnthropicMessagesAdapter,
)
from .chat_completions import ChatCompletionsHttpAdapter
from .cohere import COHERE_CHAT_ENDPOINT, CohereChatV2Adapter
from .copilot import (
    COPILOT_SDK_ENDPOINT,
    CopilotSdkAuthenticationError,
    CopilotSdkRateLimitError,
    CopilotSdkTimeoutError,
    CopilotSdkTransport,
    CopilotSdkUnavailableError,
    GitHubCopilotAdapter,
    GithubCopilotSdkTransport,
)
from .deepseek import DEEPSEEK_RESPONSES_ENDPOINT, DeepSeekResponsesAdapter
from .gemini import GEMINI_INTERACTIONS_ENDPOINT, GeminiInteractionsAdapter
from .io import (
    ProviderCredential,
    ProviderInvocationPayload,
    ProviderRequestPayloadReader,
    ProviderResponsePayloadWriter,
    StructuredOutputSpec,
    StructuredOutputValidator,
)
from .kimi import KIMI_CHAT_COMPLETIONS_ENDPOINT, KimiChatCompletionsAdapter
from .mimo import MIMO_RESPONSES_ENDPOINT, MiMoResponsesAdapter
from .mistral import MISTRAL_CHAT_COMPLETIONS_ENDPOINT, MistralChatCompletionsAdapter
from .openai import OPENAI_RESPONSES_ENDPOINT, OpenAIResponsesAdapter
from .parity import (
    CANONICAL_PROVIDER_PORT_PLAN,
    MANDATORY_ADAPTER_PARITY_GATES,
    AdapterParityGate,
    AdapterTransportFamily,
    ProviderPortPlan,
    provider_port_plan,
)
from .protocol import (
    NativeUsage,
    OutputKind,
    ProviderAdapter,
    ProviderAttemptRequest,
    ProviderAttemptResult,
    ProviderCostMetadata,
    ProviderOutcome,
    ProviderTarget,
    ProviderUsage,
)
from .qwen import QWEN_CHAT_COMPLETIONS_ENDPOINT, QwenChatCompletionsAdapter
from .registry import (
    INITIAL_PROVIDER_TAXONOMY,
    AdapterResolution,
    ProviderCapability,
    ProviderModelSpec,
    ProviderRegistry,
    ProviderRegistryError,
    ProviderRegistryReader,
    ProviderSpec,
    PublicProviderTargetMetadata,
    ReasoningProfileSpec,
    RegistryEligibilityMode,
    RegistryFailureCode,
    RequestedTargetIdentity,
    ResolvedProviderTarget,
    TargetIdentity,
)
from .responses import (
    HttpxProviderHttpTransport,
    ProviderDispatchAmbiguousError,
    ProviderHttpResponse,
    ProviderHttpTransport,
    ResponsesHttpAdapter,
)
from .simulator import (
    ORQETIA_TEST_PROVIDER,
    DeterministicTestProvider,
    SimulatorCandidate,
    SimulatorFixture,
    SimulatorFixtureExhausted,
    SimulatorFixtureMismatch,
    SimulatorInvocation,
    SimulatorScenario,
    SimulatorStep,
)
from .xai import XAI_RESPONSES_ENDPOINT, XAIResponsesAdapter

__all__ = [
    "ANTHROPIC_MESSAGES_ENDPOINT",
    "ANTHROPIC_VERSION",
    "CANONICAL_PROVIDER_PORT_PLAN",
    "COHERE_CHAT_ENDPOINT",
    "ChatCompletionsHttpAdapter",
    "CohereChatV2Adapter",
    "COPILOT_SDK_ENDPOINT",
    "CopilotSdkAuthenticationError",
    "CopilotSdkRateLimitError",
    "CopilotSdkTimeoutError",
    "CopilotSdkTransport",
    "CopilotSdkUnavailableError",
    "GitHubCopilotAdapter",
    "GithubCopilotSdkTransport",
    "DEEPSEEK_RESPONSES_ENDPOINT",
    "GEMINI_INTERACTIONS_ENDPOINT",
    "OPENAI_RESPONSES_ENDPOINT",
    "INITIAL_PROVIDER_TAXONOMY",
    "MANDATORY_ADAPTER_PARITY_GATES",
    "KIMI_CHAT_COMPLETIONS_ENDPOINT",
    "MIMO_RESPONSES_ENDPOINT",
    "MISTRAL_CHAT_COMPLETIONS_ENDPOINT",
    "AdapterParityGate",
    "AdapterTransportFamily",
    "AnthropicMessagesAdapter",
    "ORQETIA_TEST_PROVIDER",
    "AdapterResolution",
    "DeepSeekResponsesAdapter",
    "DeterministicTestProvider",
    "GeminiInteractionsAdapter",
    "HttpxProviderHttpTransport",
    "KimiChatCompletionsAdapter",
    "MiMoResponsesAdapter",
    "MistralChatCompletionsAdapter",
    "NativeUsage",
    "OpenAIResponsesAdapter",
    "OutputKind",
    "ProviderAdapter",
    "ProviderAttemptRequest",
    "ProviderCredential",
    "ProviderDispatchAmbiguousError",
    "ProviderHttpResponse",
    "ProviderHttpTransport",
    "ProviderInvocationPayload",
    "ProviderAttemptResult",
    "ProviderCapability",
    "ProviderCostMetadata",
    "ProviderModelSpec",
    "ProviderOutcome",
    "ProviderPortPlan",
    "ProviderRegistry",
    "ProviderRegistryError",
    "ProviderRegistryReader",
    "ProviderRequestPayloadReader",
    "ProviderResponsePayloadWriter",
    "ResponsesHttpAdapter",
    "ProviderSpec",
    "ProviderTarget",
    "ProviderUsage",
    "QWEN_CHAT_COMPLETIONS_ENDPOINT",
    "QwenChatCompletionsAdapter",
    "PublicProviderTargetMetadata",
    "ReasoningProfileSpec",
    "RegistryEligibilityMode",
    "RegistryFailureCode",
    "RequestedTargetIdentity",
    "ResolvedProviderTarget",
    "SimulatorCandidate",
    "SimulatorFixture",
    "SimulatorFixtureExhausted",
    "SimulatorFixtureMismatch",
    "SimulatorInvocation",
    "SimulatorScenario",
    "SimulatorStep",
    "StructuredOutputSpec",
    "StructuredOutputValidator",
    "TargetIdentity",
    "XAI_RESPONSES_ENDPOINT",
    "XAIResponsesAdapter",
    "provider_port_plan",
]
